environment:
    matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64


platform:
  - x64 # 64-bit


branches:
  only:
    - master
    - /release-.*/


install:
    - cmd: >-
        SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

        pacman -S --needed --noconfirm mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-make

        pacman -S --needed --noconfirm mingw-w64-x86_64-openblas

        pacman -S --needed --noconfirm mingw-w64-x86_64-arpack mingw-w64-x86_64-netcdf mingw-w64-x86_64-lapack mingw-w64-x86_64-szip

        wget https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-fortran-4.5.2.tar.gz

        tar -zxvf netcdf-fortran-4.5.2.tar.gz

        cd netcdf-fortran-4.5.2

        bash -c ./configure

        make

        make install

        cd ..

build_script:
    - cmd: >-
        pwd

        ls

        bash -c 'nc-config --all'

        bash -c 'nf-config --all'

        cp config.mk.template config.mk

        bash -c 'make OS=mingw STATIC=on LIBS="-L/usr/lib -llapack -larpack -lopenblas $(nf-config --flibs) $(nc-config --libs) $(nc-config --static)"'

